### ISSUE TITLE
[Minor bug] Validate does not actually check if the icon exists

### ISSUE THREAD

**Issue by SvanteRichter** [guenther/guenther#2]
Validate does not actually check if the icon exists, just if it is defined in composer.json.

Could lead to people having issues due to the icon not being in the correct path and things like that.

**Comment by PhillippOhlandt** [comment]
I do:
https://github.com/guenther/guenther/blob/master/src/Check/ComposerJsonChecker.php#L139

**Comment by SvanteRichter** [comment]
Ah, Now I see what the issue is... The bad emoji support in PuTTY don't support error or success icons, only the warning, so both error and success icons look the same here, and therefore I missed it... Sorry, closing issue.

**Comment by PhillippOhlandt** [comment]
Ah ok. Will add a parameter to disable emojis in the output in the next version.
